version: 2

project_name: kratos

env:
  - GO111MODULE=on

builds:
  - id: alpine-cgo-amd64
    flags:
      - "-tags=sqlite,hsm,json1"
    ldflags:
      - "-s -w -X github.com/ory/kratos/driver/config.Version={{.Tag}} -X github.com/ory/kratos/driver/config.Commit={{.FullCommit}} -X github.com/ory/kratos/driver/config.Date={{.Date}}"
    binary: "{{ .ProjectName }}"
    env:
      - CGO_ENABLED=1
      - CC=musl-gcc
    goarch:
      - amd64
    goos:
      - linux

dockers:
  - image_templates:
      - "oryd/{{ .ProjectName }}:v{{ .Version }}-amd64"
    use: buildx
    dockerfile: ".docker/Dockerfile-alpine"
    goarch: amd64
    ids:
      - alpine-cgo-amd64
    build_flag_templates:
      - "--label=org.opencontainers.image.title={{ .ProjectName }}"
      - "--label=org.opencontainers.image.vendor=Ory"
      - "--label=org.opencontainers.image.version={{ .Version }}"
      - "--label=org.opencontainers.image.created={{ .Date }}"
      - "--label=org.opencontainers.image.source={{ .GitURL }}"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
      - "--label=org.opencontainers.image.url=https://www.ory.sh"
      - "--label=org.opencontainers.image.documentation=https://www.ory.sh/docs"
      - "--platform=linux/amd64"
